name: Release

on:
  push:
    tags:
      - 'v*'  # 예: v1.0.0 같은 태그가 푸시될 때 트리거됨

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o dist/register-cli-linux

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o dist/register-cli-macos

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o dist/register-cli.exe

      - name: Copy install.sh
        run: cp install.sh dist/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/register-cli-linux
            dist/register-cli-macos
            dist/register-cli.exe
            dist/install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
